New custom analytics
jamf/jamfprotect pull request #17
Opened 2022-02-15 11:12 UTC by matt-taylor934

New custom analytics to report on:
- usage of the caffeinate binary on an interactive command line, due to a concern where a user may leave their machine awake and unlocked
- file sharing being enabled or disabled
- the root user being enabled or the password of an enabled root user being changed
- suspicious xattr activity where either all extended attributes are cleared or the com.apple.quarantine attribute cleared from a file

2022-02-15 18:02 UTC, jbradley89 requested changes

2022-02-15 18:02 UTC, jbradley89 commented on custom_analytic_detections/system_config_activity/file_sharing_config_changes
> +$event.type == 1 AND $event.process.signingInfo.appid == "com.apple.xpc.launchctl" AND $event.process.args CONTAINS[cd] "load" AND $event.process.args CONTAINS[cd] "/System/Library/LaunchDaemons/com.
Same as above

2022-02-16 12:08 UTC, matt-taylor934 commented on custom_analytic_detections/system_config_activity/file_sharing_config_changes
> +$event.type == 1 AND $event.process.signingInfo.appid == "com.apple.xpc.launchctl" AND $event.process.args CONTAINS[cd] "unload" AND $event.process.args CONTAINS[cd] "/System/Library/LaunchDaemons/co
Just tested this and both do work as they're written in the commit, tested by turning FS off and on again a few times inside Sys Prefs.

Also tested your version for both and it also works so happy to swap to this if it's the preferred syntax.  Is there any reason we wouldn't add spaces before / after the plist path value?  Doing this caused it to fail whereas doing spaces just for 'unload' and 'load' worked fine.

2022-02-16 12:10 UTC, matt-taylor934 commented on custom_analytic_detections/system_config_activity/file_sharing_config_changes
> +$event.type == 1 AND $event.process.signingInfo.appid == "com.apple.xpc.launchctl" AND $event.process.args CONTAINS[cd] "load" AND $event.process.args CONTAINS[cd] "/System/Library/LaunchDaemons/com.
Replied above

2022-02-16 17:54 UTC, matt-taylor934 commented
Predicates updated as requested.

2022-02-16 18:09 UTC, saljooki approved these changes

2022-02-16 18:17 UTC, stuartjash approved these changes

2022-02-16 18:46 UTC, jbradley89 approved these changes

2022-02-17 09:19 UTC, merged