new api scripts
jamf/jamfprotect pull request #22
Opened 2022-04-28 16:52 UTC by golbiga

New API Scripts:

- send_slack_webhook_analytics
-send_teams_webhook_analytics

2022-05-09 22:10 UTC, bobobox commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +        slack_webhook(new_analytic['uuid'],new_analytic['name'],new_analytic['severity'],new_analytic['description'],new_analytic['jamf'],new_analytic['created'],new_analytic['updated'])
indentation seems wrong here

2022-05-09 22:10 UTC, bobobox commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +        analyticType = "Updated"
I think a more reliable way to determine if an Analytic is new or just updated would be to look at both `uuid` and `hash`... use finding a new `uuid` to determine if an analytic is new, and if the `hash` has changed to determine if it has updated.

With the way you're doing it above, an analytic could be classed as `Updated` when it's actually new from the POV of the script, if it was added and then updated between invocations of this script. Not likely, but using `uuid` seems more reliable.

2022-05-09 22:11 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +#!/usr/bin/env python3
Potentially could be the same script as the Slack one, just with an option to send to one or the other (or both) services?

2022-05-09 23:13 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +#!/usr/bin/env python3
I think keeping it separate might be best. This way it aligns with what an organization supports internally.

2022-05-10 00:31 UTC, golbiga commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +    if os.path.exists('/tmp/analytics.json') == False:
Good, point. Fixed.

2022-05-10 00:38 UTC, golbiga commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +# - Writes the list to a temporary json file (created on first run of the script)
understood, removing all mentions of temporary or temp

2022-05-10 00:39 UTC, golbiga commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +        jamfText="Jamf"
That works, also a much cleaner.

2022-05-10 00:43 UTC, golbiga commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +        slack_webhook(new_analytic['uuid'],new_analytic['name'],new_analytic['severity'],new_analytic['description'],new_analytic['jamf'],new_analytic['created'],new_analytic['updated'])
Not seeing any errors related to indentation in vscode

2022-05-10 15:58 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +#!/usr/bin/env python3
OK, was just thinking it was mostly the same, but understand wanting to keep it simple for the end user.

2022-05-11 18:39 UTC, golbiga commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +        slack_webhook(new_analytic['uuid'],new_analytic['name'],new_analytic['severity'],new_analytic['description'],new_analytic['jamf'],new_analytic['created'],new_analytic['updated'])
installed black and formatting adjusted

2022-05-11 22:28 UTC, bobobox requested changes

2022-05-11 22:28 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    ):
Can just do:
```suggestion
    if not os.path.exists("/var/tmp/jamf-protect-analytics-update-teams-webhook.json"):
```

2022-05-11 22:28 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +            json.dump(jamf_analytics_dict, output)
Can `return` here, I think. Nothing else should happen since the data on disk will be the same.

2022-05-11 22:28 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    # Check diff betweetn json json file and new pull
```suggestion
    # Check diff between json file and new pull
```

2022-05-11 22:28 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    new_jamf_analytics = set(jamf_analytics_dict).difference(output)
Technically this is `new_or_updated_analytics`. 

Could go the other way to see if a Jamf analytic was deleted too... although I think that's a pretty rare occurrence.

2022-05-11 22:28 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    print(f"New analytics available.")
Again, new or updated, not just new...

2022-05-11 22:28 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +        if any(new_analytic["uuid"] in d.values() for d in output.values()):
What you have will probably work 99.9999999% of the time but seems more straightforward to compare the uuids specifically rather than all the values.
```suggestion
        if any(new_analytic["uuid"] == old_analytic["uuid"] for old_analytic in output.values()):
```

2022-05-11 22:28 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +        os.remove("/var/tmp/jamf-protect-analytics-update-teams-webhook.json")
This doesn't look right... We don't want to delete the JSON file, but we _should_ write out to it at the end for the next time (outside of this loop).

2022-05-11 23:35 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +        os.remove("/var/tmp/jamf-protect-analytics-update-teams-webhook.json")
Do you mean clear the file out or do one last pull to update the contents of the file for the next run?

2022-05-11 23:38 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    # Check diff betweetn json json file and new pull
Fixed.

2022-05-12 00:56 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    ):
fixed.

2022-05-12 00:57 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    # Check diff betweetn json json file and new pull
fixed

2022-05-12 00:57 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    print(f"New analytics available.")
fixed

2022-05-12 00:57 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +        if any(new_analytic["uuid"] in d.values() for d in output.values()):
fixed

2022-05-12 00:57 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +        os.remove("/var/tmp/jamf-protect-analytics-update-teams-webhook.json")
writing an update to the file, so on the next check it will compare against last.

2022-05-12 00:57 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    new_jamf_analytics = set(jamf_analytics_dict).difference(output)
fixed

2022-05-12 00:58 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +            json.dump(jamf_analytics_dict, output)
fixed

2022-05-12 15:33 UTC, bobobox commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +    with open("/var/tmp/analytics.json", "w") as output:
Different file name than above...

2022-05-16 13:55 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
>              json.dump(jamf_analytics_dict, output)
fixed logic. let me know what you think.

2022-05-16 13:55 UTC, golbiga commented on jamf_protect_api/scripts/python/send_teams_webhook_analytics.py
> +        return
removed with logic change.

2022-05-18 15:50 UTC, bobobox approved these changes

2022-05-18 15:50 UTC, bobobox commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +    print(f"Generating JSON file for next run.")
f-string not needed if you're not doing any string formatting
```suggestion
    print("Generating JSON file for next run.")
```

2022-05-18 15:50 UTC, bobobox commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +        "/var/tmp/jamf-protect-analytics-update-slack-webhook.json", "w"
Definitely think this should be a variable - repeating a long path 3 times separately is one of those things that will bite you eventually :)

2022-05-18 17:14 UTC, golbiga commented on jamf_protect_api/scripts/python/send_slack_webhook_analytics.py
> +        "/var/tmp/jamf-protect-analytics-update-slack-webhook.json", "w"
fixed

2022-05-18 17:17 UTC, bobobox approved these changes

2022-05-18 18:16 UTC, merged