new api scripts
jamf/jamfprotect pull request #30
Opened 2022-07-12 18:52 UTC by golbiga

New API Scripts: 

* update_alert_status
* generate_device_controls_report

2022-10-04 18:43 UTC, bobobox commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +# - Completes a listAlerts query request that returns all logs reported to Jamf
We retired the concept of 'logs' from Protect, so it's all just alerts now.
Also should probably mention the date cutoff.

2022-10-04 18:43 UTC, bobobox commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +    with open(JSON_OUTPUT_FILE, "r") as f:
What is purpose of reading the data back in from the JSON file, as we still have it in memory as `results`?

2022-10-04 18:43 UTC, bobobox commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +            json_list = json.loads(o["json"])
Would probably call this `raw_json` or something, not a `list` as it isn't one.

2022-10-04 18:43 UTC, bobobox commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +    os.remove(JSON_OUTPUT_FILE)
If we are deleting the JSON at the end, why are we creating it at all?

2022-10-04 18:43 UTC, bobobox commented on jamf_protect_api/scripts/python/update_alert_status.py
> +    ALERT_UUID = args.uuid.split(",")
I think it might be wise to set an upper limit here, or at least split the input into batches of reasonable size (100 maybe?). 
Also, given that there may be a lot of alerts here, could this be a place where we could read in a CSV or something? Just saw a message about a customer with 55,000 alerts... i worry about what happens when they try putting that in as a CLI argument :P

2022-10-05 00:14 UTC, golbiga commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +            json_list = json.loads(o["json"])
Done.

2022-10-05 00:16 UTC, golbiga commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +# - Completes a listAlerts query request that returns all logs reported to Jamf
Done.

2022-10-05 00:31 UTC, golbiga commented on jamf_protect_api/scripts/python/update_alert_status.py
> +    ALERT_UUID = args.uuid.split(",")
I think maybe just setting a limit for now.

2022-10-05 01:21 UTC, golbiga commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +    with open(JSON_OUTPUT_FILE, "r") as f:
Good question :) Removed the json file altogether and reading from results.

2022-10-05 01:25 UTC, golbiga commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +    os.remove(JSON_OUTPUT_FILE)
Removed.

2022-10-05 16:16 UTC, bobobox requested changes

2022-10-05 16:16 UTC, bobobox commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +# - Exports alert data in JSON format to Jamf_Protect_Device_Controls_alerts_{Date}.json
```suggestion
```

2022-10-05 16:16 UTC, bobobox commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +        rows = [
Mixing up singular and plural in names causes confusion - this is defining a single row:
```suggestion
        row = [
```

2022-10-05 16:16 UTC, bobobox commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +    print(f"Writing results to '{CSV_OUTPUT_FILE}'")
I think I'd probably print this before you start writing (ie around line 134), rather than after you're done.
That way if it takes a while or if something blows up, the user has an idea of what's going on.

2022-10-05 16:16 UTC, bobobox commented on jamf_protect_api/scripts/python/update_alert_status.py
> +        "--uuid",
Again, just my singular/plural nitpickiness
```suggestion
        "--uuids",
```

2022-10-05 16:16 UTC, bobobox commented on jamf_protect_api/scripts/python/update_alert_status.py
> +        print("Maximum number of uuids is 100. Please try again.")
Generally better structure to put conditions like this at the top, ie:

```
if len(ALERT_UUID) > 100:
    print("Maximum number of UUIDs is 100. Please try again.")
    sys.exit(1)
```

And then you don't need to put the bulk of the code inside an if-statement, plus the requirements are near the start.

2022-10-06 00:11 UTC, golbiga commented on jamf_protect_api/scripts/python/update_alert_status.py
> +        "--uuid",
done

2022-10-06 00:17 UTC, golbiga commented on jamf_protect_api/scripts/python/update_alert_status.py
> +        print("Maximum number of uuids is 100. Please try again.")
Done.

2022-10-06 00:25 UTC, golbiga commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +        rows = [
done

2022-10-06 00:26 UTC, golbiga commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +    print(f"Writing results to '{CSV_OUTPUT_FILE}'")
done

2022-10-06 00:30 UTC, golbiga commented on jamf_protect_api/scripts/python/generate_device_controls_report.py
> +# - Exports alert data in JSON format to Jamf_Protect_Device_Controls_alerts_{Date}.json
done

2022-10-06 00:39 UTC, bobobox commented on jamf_protect_api/scripts/python/update_alert_status.py
> +    else:
Don't need an 'else' here

2022-10-06 01:11 UTC, golbiga commented on jamf_protect_api/scripts/python/update_alert_status.py
> +    else:
oops, fixed

2022-10-06 01:54 UTC, bobobox approved these changes

2022-10-06 01:55 UTC, merged